version: '3' 
services: 
  homeassistant: 
    container_name: homeassistant 
    image: "ghcr.io/home-assistant/home-assistant:stable" 
    volumes:
      - .homeassistant:/config 
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /share:/share
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped 
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    network_mode: host
    command: /bin/sh -c "apk add gcc musl-dev bluez-dev ; /init"
